FROM screamingjoypad/BASENAME
#TODO - changee this BASNAME to the actual docker hub location/name of the bas image

# The only thing that this image needs to do is
# expore network port 1099 and 50000, this is how the 
# Serveer node communicates with the Master nodes
EXPOSE 1099 50000

# Here we will start the JMeter-server app to start
# whenever the image starts.
ENTRYPOINT /jmeter/apache-jmeter-3.3/bin/jmeter-server \
                        -Dserver.rmi.localport=50000 \
                        -Dserver_port=1099